import { StyleSheet } from 'react-native';

export const palette = {
  background: '#FFF6EF',
  surface: '#FFFFFF',
  surfaceMuted: '#FFF1E6',
  ink: '#1F2937',
  inkSoft: '#667085',
  inkMuted: '#94A3B8',
  accent: '#FF7A1A',
  accentDeep: '#E95E00',
  accentSoft: '#FFE5D0',
  border: '#E8D9CC',
  borderStrong: '#F6B27F',
  danger: '#D64545',
  dangerSoft: '#FFE3E0',
  success: '#0F9D77',
  successSoft: '#D9FAEF',
  info: '#1D4ED8',
  infoSoft: '#E7F0FF',
  shadow: 'rgba(15, 23, 42, 0.12)',
};

export const authSharedStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.background,
  },
  screenFrame: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 20,
  },
  screenPadding: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 20,
  },
  screenPaddingKeyboard: {
    paddingTop: 4,
    paddingBottom: 12,
  },
  backgroundOrbPrimary: {
    position: 'absolute',
    top: -54,
    right: -24,
    width: 136,
    height: 136,
    borderRadius: 68,
    backgroundColor: '#FFD8BA',
    opacity: 0.78,
  },
  backgroundOrbSecondary: {
    position: 'absolute',
    bottom: 38,
    left: -32,
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#FFE9D8',
    opacity: 0.9,
  },
  pageChrome: {
    flexGrow: 1,
    gap: 14,
    width: '100%',
    maxWidth: 460,
    alignSelf: 'center',
  },
  pageChromeCompact: {
    gap: 12,
  },
  pageChromeKeyboard: {
    gap: 8,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  topBarKeyboard: {
    marginBottom: 2,
  },
  cardRail: {
    flexGrow: 1,
  },
  cardRailCompact: {
    minHeight: 0,
  },
  cardRailKeyboard: {
    flexGrow: 0,
  },
  brandChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.94)',
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 4,
  },
  brandMark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.accentSoft,
  },
  brandMarkInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: palette.accent,
  },
  brandText: {
    fontSize: 14,
    fontWeight: '700',
    color: palette.ink,
  },
  formCard: {
    flexShrink: 1,
    borderRadius: 26,
    backgroundColor: palette.surface,
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: '#F1E5DA',
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 8,
  },
  formCardCompact: {
    paddingHorizontal: 17,
    paddingVertical: 14,
    gap: 10,
  },
  formCardKeyboard: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 7,
  },
  cardContentScroll: {
    gap: 10,
    paddingTop: 2,
    paddingBottom: 4,
  },
  cardContentScrollKeyboard: {
    gap: 8,
    paddingBottom: 0,
  },
  introBlock: {
    gap: 8,
  },
  introBlockKeyboard: {
    gap: 4,
  },
  introTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  introTopRowKeyboard: {
    marginBottom: 0,
  },
  introBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
  },
  introBadgeKeyboard: {
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  introBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: palette.accentDeep,
    letterSpacing: 0.3,
  },
  introBadgeTextKeyboard: {
    fontSize: 10,
  },
  introIconFrame: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: palette.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  introIconFrameKeyboard: {
    width: 38,
    height: 38,
    borderRadius: 12,
  },
  introIconHalo: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFF7F2',
    borderWidth: 3,
    borderColor: '#FFA96A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  introIconHaloKeyboard: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  introIconCore: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.accent,
  },
  introTitle: {
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '800',
    color: palette.ink,
  },
  introTitleKeyboard: {
    fontSize: 17,
    lineHeight: 21,
  },
  introSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.inkSoft,
  },
  tabs: {
    flexDirection: 'row',
    gap: 6,
    padding: 4,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
  },
  tabsKeyboard: {
    marginTop: 0,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    paddingVertical: 10,
  },
  tabButtonActive: {
    backgroundColor: palette.surface,
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 2,
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: palette.inkMuted,
  },
  tabButtonTextActive: {
    color: palette.ink,
  },
  banner: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },
  bannerKeyboard: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  bannerInfo: {
    backgroundColor: palette.infoSoft,
  },
  bannerError: {
    backgroundColor: palette.dangerSoft,
  },
  bannerSuccess: {
    backgroundColor: palette.successSoft,
  },
  bannerLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  bannerLabelInfo: {
    color: palette.info,
  },
  bannerLabelError: {
    color: palette.danger,
  },
  bannerLabelSuccess: {
    color: palette.success,
  },
  bannerMessage: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.ink,
  },
  inlineInfoActions: {
    alignItems: 'flex-start',
    marginTop: -2,
  },
  inlineInfoTrigger: {
    paddingVertical: 4,
  },
  inlineInfoTriggerText: {
    color: palette.accentDeep,
    fontSize: 13,
    fontWeight: '700',
  },
  inlineInfoCard: {
    gap: 4,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(29, 78, 216, 0.16)',
    backgroundColor: palette.infoSoft,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inlineInfoTitle: {
    color: palette.info,
    fontSize: 13,
    fontWeight: '800',
  },
  inlineInfoBody: {
    color: palette.ink,
    fontSize: 13,
    lineHeight: 18,
  },
  inlineInfoDetail: {
    color: palette.inkSoft,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  stepFlowHeader: {
    gap: 6,
    paddingBottom: 2,
  },
  stepFlowBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#FFF0E2',
  },
  stepFlowBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: palette.accentDeep,
  },
  stepFlowTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: palette.ink,
  },
  stepFlowDescription: {
    fontSize: 12,
    lineHeight: 17,
    color: palette.inkSoft,
  },
  stepFlowStack: {
    gap: 10,
  },
  minimalRegisterLayout: {
    flex: 1,
    gap: 28,
    paddingTop: 34,
    paddingBottom: 28,
  },
  minimalRegisterLayoutKeyboard: {
    gap: 18,
    paddingTop: 20,
    paddingBottom: 14,
  },
  minimalRegisterHeader: {
    gap: 10,
  },
  minimalRegisterEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
    color: palette.accentDeep,
    textTransform: 'uppercase',
  },
  minimalRegisterTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '800',
    color: palette.ink,
  },
  minimalRegisterSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.inkSoft,
  },
  minimalRegisterSubtitleSuccess: {
    color: palette.success,
  },
  minimalRegisterSubtitleError: {
    color: palette.danger,
  },
  minimalRegisterFlow: {
    gap: 16,
  },
  minimalRegisterStage: {
    gap: 18,
  },
  minimalRegisterStageKeyboard: {
    flex: 1,
    minHeight: 0,
    justifyContent: 'flex-end',
  },
  minimalRegisterSummaryScroll: {
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 0,
  },
  minimalRegisterSummaryContent: {
    gap: 12,
    paddingBottom: 12,
  },
  minimalRegisterCurrentSection: {
    flexShrink: 0,
    gap: 10,
  },
  stepCurrentField: {
    gap: 2,
  },
  minimalStepCurrentField: {
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EADFD4',
  },
  stepSummaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: '#FFF7F1',
    borderWidth: 1,
    borderColor: '#F2DDCB',
  },
  stepSummaryTextWrap: {
    flex: 1,
    gap: 2,
  },
  stepSummaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: palette.inkSoft,
  },
  stepSummaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: palette.ink,
  },
  stepSummaryAction: {
    marginLeft: 12,
    fontSize: 12,
    fontWeight: '700',
    color: palette.accentDeep,
  },
  minimalStepSummary: {
    alignItems: 'flex-start',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EFE4D9',
  },
  minimalStepSummaryTextWrap: {
    flex: 1,
    gap: 4,
  },
  minimalStepSummaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: palette.inkSoft,
    letterSpacing: 0.2,
  },
  minimalStepSummaryValue: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: palette.ink,
  },
  minimalInlineError: {
    paddingVertical: 4,
  },
  minimalInlineErrorText: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.danger,
  },
  formBody: {
    gap: 10,
  },
  formBodyKeyboard: {
    gap: 6,
  },
  field: {
    gap: 4,
  },
  fieldMinimal: {
    gap: 8,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.ink,
  },
  fieldLabelMinimal: {
    fontSize: 11,
    letterSpacing: 0.2,
    color: palette.inkSoft,
  },
  inputShell: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: '#FAFAFA',
    paddingHorizontal: 13,
  },
  inputShellMinimal: {
    minHeight: 0,
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#D9CEC3',
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingBottom: 10,
  },
  inputShellFocused: {
    borderColor: palette.borderStrong,
    backgroundColor: '#FFFFFF',
  },
  inputShellFocusedMinimal: {
    borderColor: '#D9CEC3',
    borderBottomColor: palette.accentDeep,
    backgroundColor: 'transparent',
  },
  inputShellError: {
    borderColor: palette.danger,
    backgroundColor: '#FFF8F8',
  },
  inputShellErrorMinimal: {
    borderColor: '#D9CEC3',
    borderBottomColor: palette.danger,
    backgroundColor: 'transparent',
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: palette.ink,
    paddingVertical: 0,
  },
  textInputMinimal: {
    fontSize: 30,
    fontWeight: '700',
    color: palette.ink,
    paddingVertical: 0,
  },
  fieldAction: {
    marginLeft: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
  },
  fieldActionIconButton: {
    width: 38,
    height: 38,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F2D8C2',
    backgroundColor: '#FFF8F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldActionMinimal: {
    marginLeft: 12,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  fieldActionIconButtonMinimal: {
    width: 34,
    height: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#F5DDC8',
    backgroundColor: '#FFF9F4',
  },
  fieldActionText: {
    fontSize: 11,
    fontWeight: '700',
    color: palette.accentDeep,
  },
  fieldActionTextMinimal: {
    fontSize: 13,
  },
  visibilityIcon: {
    width: 20,
    height: 12,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  visibilityIconMinimal: {
    width: 18,
    height: 11,
  },
  visibilityIconActive: {
    opacity: 1,
  },
  visibilityIconUpperArc: {
    position: 'absolute',
    top: 0,
    width: '100%',
    height: 7,
    borderTopWidth: 1.8,
    borderLeftWidth: 1.8,
    borderRightWidth: 1.8,
    borderColor: palette.accentDeep,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
  },
  visibilityIconLowerArc: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 7,
    borderBottomWidth: 1.8,
    borderLeftWidth: 1.8,
    borderRightWidth: 1.8,
    borderColor: palette.accentDeep,
    borderBottomLeftRadius: 999,
    borderBottomRightRadius: 999,
  },
  visibilityIconIris: {
    width: 5.5,
    height: 5.5,
    borderRadius: 3,
    backgroundColor: palette.accentDeep,
  },
  visibilityIconSlash: {
    position: 'absolute',
    width: 24,
    height: 2,
    borderRadius: 999,
    backgroundColor: palette.accentDeep,
    transform: [{ rotate: '-32deg' }],
  },
  fieldMessage: {
    fontSize: 11,
    lineHeight: 15,
  },
  fieldMessageMinimal: {
    paddingTop: 2,
  },
  fieldMessageNeutral: {
    color: palette.inkSoft,
  },
  fieldMessageSuccess: {
    color: palette.success,
  },
  fieldMessageError: {
    color: palette.danger,
  },
  primaryButton: {
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF7A1A',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 5,
  },
  primaryButtonDisabled: {
    backgroundColor: '#F8B98D',
    shadowOpacity: 0,
    elevation: 0,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  secondaryLinkWrap: {
    alignItems: 'center',
  },
  secondaryLinkButton: {
    minHeight: 42,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#F2D8C2',
    backgroundColor: '#FFF4EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryLinkText: {
    fontSize: 13,
    fontWeight: '700',
    color: palette.accentDeep,
  },
});
